execute pathogen#infect()
call pathogen#helptags()

" GENERAL OPTIONS
behave xterm
let mapleader = ","
set viminfo='20,\"500,%	" ' Maximum number of previously edited files for which the marks
			"   are remembered.  
			" " Maximum number of lines saved for each register.
			" % When included, save and restore the buffer list.  If Vim is
			"   started with a file name argument, the buffer list is not
			"   restored.  If Vim is started without a file name argument, the
			"   buffer list is restored from the viminfo file.  Buffers
			"   without a file name and buffers for help files are not written
			"   to the viminfo file.
set history=500		" keep {number} lines of command line history
" set nowrap              " whether to wrap lines
			"  commands
colorscheme ir_black

if &t_Co > 2 || has("gui_running")
   syntax on
endif

set pastetoggle=<F2>
set nocompatible
set incsearch
set showmatch
set backspace=1
syntax on

set cinoptions=:0,p0,t0
set cinwords=if,unless,else,while,until,do,for,switch,case
set formatoptions=tcqr

" VIM DISPLAY OPTIONS
" set showmode		" show which mode (insert, replace, visual)
" set ruler
" set title
" set showcmd		" show commands in status line when typing
" set wildmenu	

set modelines=0
set tabstop=3
set shiftwidth=3
set softtabstop=3
set expandtab

set encoding=utf-8
set scrolloff=3
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile

set wrap
set linebreak
set textwidth=89
set formatoptions=qrn1
set colorcolumn=90

nnoremap ; :
" searching things
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

nnoremap j gj
nnoremap k gk

inoremap jj <ESC>
inoremap jJ <ESC>
inoremap JJ <ESC>
inoremap Jj <ESC>

autocmd BufNewFile,BufReadPost *.ino,*.pde set filetype=cpp 
autocmd BufNewFile,BufReadPost *.less set filetype=css 
autocmd BufNewFile,BufReadPost *.tex set filetype=tex
autocmd BufNewFile,BufRead *.json set filetype=javascript
" support for differing indentation based on filetype
filetype plugin indent on

